DROP TABLE IF EXISTS `sys_user`;

CREATE TABLE `sys_user`
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    name VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
    profile VARCHAR(150) NULL DEFAULT NULL COMMENT '头像',
    email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
    PRIMARY KEY (id)
);