# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogbacken
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
  sql:
    init:
      mode: always
      schema-locations: classpath:/static/db/schema.sql
      data-locations: classpath:/static/db/data.sql
